### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [Jacuzzy/prj-rev-bwfs-dasmoto#5]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. There are several shared properties in the CSS, so you might simplify it like so

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}

h1, .image{
  font-size: 100px;
  color: khaki;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

strong {
  color: blue;
}
```
